# Site settings
name: 数据之道
title: 数据之道 | guruguru.cn
description: "专注于数据技术，分享数据领域的技术实践，跟踪数据技术的发展趋势，解读数据相关的法律法规"
keywords: "数据之道，数据技术，数据平台，数据治理，guruguru.cn"
url: "https://guruguru.cn" # your host, for absolute URL
baseurl: "" # The defaults is empty, '/blog' if your blog hosted on 'host/blog'

# 作用于 pages 和 collections；对于 pages，`:title` 等同于 `:basename`，而且会默认前置 `/:path/`
permalink: pretty # => `/:categories/:year/:month/:day/:title/`

# Front matter defaults
defaults:
  - scope:
      path: "" # All pages and collections
    values:
      banner: "/assets/img/banner/post.jpeg" # default banner for pages and documents
  - scope:
      path: ""
      type: posts # The "posts" collection => "_posts" directory
    values:
      layout: post
      permalink: /:year/:month/:title:output_ext # 优先级高于: `collections.posts.permalink`
  - scope:
      path: ""
      type: pages # All pages
    values:
      layout: page
      permalink: /:path/:basename:output_ext # defaults: `/:path/:basename/` (output_ext: .md=>.html, .html=>.html, .x=>.x)

# Publish posts or collection documents with a future date.
future: true
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Paging settings
paginate: 10
paginate_path: "/page/:num/"

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - CNAME
  - LICENSE
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - assets/less
  - Gruntfile.js
  - node_modules
  - package*.json
  - Gemfile*
  - vendor

# Gems, <https://pages.github.com/versions>
plugins:
  - jemoji # :+1:
  - jekyll-feed # {% feed_meta %} and /feed.xml
  - jekyll-paginate
  - jekyll-sitemap # /robots.txt and sitemap.xml
  - jekyll-seo-tag # {% seo %}
  - jekyll-redirect-from
  - jekyll-relative-links

#=========================== Plugins settings ===========================#

# jekyll-sitemap plugin
sitemap: true

# jekyll-feed plugin
feed:
  path: feed.xml # It's the default

#=========================== more settings ===========================#

# Site Language
lang: "zh-cmn-Hans" # "zh-cmn-Hans" => 简体中文; "zh-cmn-Hant" => 繁体中文; "en" => English

# Default banner for all pages
banner: "assets/img/banner/post.jpeg"

author:
  name: jinsyin
  email: jinsyin@gmail.com
  github: https://github.com/jinsyin

# Home page's sidebar settings
sidebar:
  enable: true # true => 右侧； false => 底部（不包含 Short About）
  featured-tags:
    enable: true # whether or not using Feature-Tags
    condition-size: 1 # A tag will be featured if the size of it is more than this condition value
  aboutme:
    enable: true
    avatar: /assets/img/avatar/wechat-mp.jpg # use absolute URL
    description: "发现问题、思考问题、解决问题"
    enable-socials: true
  friends:
    enable: true

analytics:
  google:
    enable: false
    track_id: "UA-111111-22"
    domain: guruguru.cn
    site-verification: ""
  baidu:
    enable: false
    track_id: "xxxxxx"

# Site verification
verification:
  google: null
  bing: "D614E69F82B9CF64B3EF4F8DF0E26432"
  baidu: "5Rjv9HSAa8"
  sogou: "DMkNnyycVE"
  so: "9c2075914f6a2574f6462ac441664701" # 360 搜索
  shenma: "e25a2659ef58e536e10166869b793e01_1577531111" # 神马

# Disqus settings
disqus:
  enable: false
  username: jinsyin

anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false
